name: todo
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.0
  awesome_notifications: ^0.9.3+1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  fluttertoast: ^8.2.4
  provider: ^6.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - assets/images/myicon.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 